Spliit:
  match: "Split mode"
  hdr:
    date: 'Date'
    desc: 'Description'
    category: 'Category'
    debit: 'Katie' 
    total: 'Cost' # Debit and cost are used to compute actual line item
  negative_debit: True
  rules: 'expenses_credit.csv'
Splitwise:
  match: 'Katie'
  hdr:
    date: 'Date'
    desc: 'Description'
    category: 'Category'
    debit: 'Katie'
  negative_debit: True
  rules: 'expenses_splitwise.csv'
CapitalOne:
  match: 'Card No'
  hdr:
    date: 'Transaction Date'
    desc: 'Description'
    category: 'Category'
    debit: 'Debit'
  negative_debit: False
  rules: 'expenses_credit.csv'
Splitwise Empty: 
  match: 'You have no '
  pass: True
Amex:
  match: 'Card Member'
  hdr:
    date: 'Date'
    desc: 'Description'
    category: ''
    debit: 'Amount'
  negative_debit: False
  rules: 'expenses_credit.csv'
